{% set version = "1.8.5" %}

package:
    name: pyflann
    version: {{ version }}

source:
    fn: flann-{{ version }}.tar.gz
    url: https://github.com/mariusmuja/flann/archive/{{ version }}.tar.gz
    sha256: 59a9925dac0705b281496ae52b5dfd79d6b69316d37015e3d3b38c859bac4f2f

build:
    number: 0
    skip: true  # [win]

requirements:
    build:
        - python
        - setuptools
        - flann {{ version }}
        - cmake
    run:
        - python
        - flann {{ version }}
        - numpy

test:
    imports:
        - pyflann

about:
    home: http://www.cs.ubc.ca/research/flann/
    license: BSD 3-Clause
    license_file: COPYING
    summary: "Python wrapper for FLANN"

extra:
  recipe-maintainers:
    - jakevdp
    - jakirkham
