travis:
  secure:
    BINSTAR_TOKEN: jW4scf3v8xqn/x63rd/bszYHdaJxV1ckgZTHbWnsg82Bdue354yN7dWYbvRiyImMdXnZfksRIZ1wqPYYhrJDrutxPvV7spFYXdo9MuIklojBBV2hYvxffxnR8HXDxUSmjXmu0bJ2006qjaNh1nc6alnOiK7EpgcBv5dO9ER7gSY+lCt2RVSyVNqHZK7hDpPV0Y68bCGw0DNG6K2T11e6V90gwcPxmCQWoG5ckJF73aeXJZh1h3ORXXun75bu3KPjd8hSsnBraInCNYq8cBcQfJWw1zQeFtafudbLjVyMKHQzz6WzTOK178MvZA+dm2JxcxYapo3/0LWUkNaFrlsiNVHedIdHHGhjYXW9+D6mlldelbn25UsnHKHSktyGY6iarpdebmkVY1DGFN0lbXZx9I1i+KVi7louHRVIk9//UoOA7YySvcnHQme1MzxQvxf7TFWLZ8fsqlQhexkFtLJZFaC0N+D9TUP9GzmlGKpITd0SygAINr0AVX0brLsdJPXORXuWWjdg3vxBEz3b0fpeEV7/KOEegTf1Q6itWvMeiT/h97/RcbQ0v9RJeESqxZwWjCsq5sTH6Om4yWnaVWwXzK8X/qwKm8EwpH7LsCBp71fRqyXE5gpdZ7fnJzblqj7G/lCXocLnwVC1ZCRL6pIeGO8WVGo+bRDsrvk8n0z483Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
